### ISSUE TITLE
errors in file rnn_order_size_gmm.py

### ISSUE THREAD

**Issue by zkk995** [sjvasquez/instacart-basket-prediction#3]
1.   please check the  line 159 . I think  the log_likelihood should be 0-dimensional tensor.  right?
```
log_likelihood = -tf.log(tf.reduce_sum(mixing_coefs*n_likelihoods, axis=2) + 1e-10)
```
2.  another error in this file:  the definition of `data_cols` in line 17

**Comment by sjvasquez** [comment]
You're correct.  These errors resulted from some sloppy copy and paste refactoring.  Should be fixed now.
